dotenv: .env
wallets :
  key : ${PRIVATE_KEY}

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.5.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.5.1'
networks:
  goerli:
    eth_usd_price_feed : "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    verify : True
  development:
    verify : False
